### ISSUE TITLE
What is a "valid" data folder?

### ISSUE THREAD

**Issue by Ryuukarin** [Affectiva/cpp-sdk-samples#22]
Hi,
I'm trying to run the video-demo code from the cpp-sdk-samples. I get the error message "Failed to initialize, invalid data folder" (from the detector->start(); execution, I guess).
If I understand well, the data folder is smthng/affdex-sdk/data, isn't it? If yes, please explain where to specify it exactely and how should it be formatted (for example, is it ok if there are blancs in the path?)
Thank you.

**Comment by adennie** [comment]
Hi, you just need to specify the location of the data folder in the
detector.setClassifierPath() call. See
http://developer.affectiva.com/v3_4_1/windows/analyze-video/ for some
additional details.

In the video demo app, the data folder is passed to the app on the
command line, via the value supplied with the -d (or -data) command line
argument. See
https://github.com/Affectiva/cpp-sdk-samples/blob/master/video-demo/video-demo.cpp.

-Andy



Ryuukarin wrote:

**Comment by Ryuukarin** [comment]
Many thanks Adennie, specifying the location of the data folder in the
detector.setClassifierPath() call works fine.
