### ISSUE TITLE
detector->stop blocking for ever

### ISSUE THREAD

**Issue by nikhilvs** [Affectiva/cpp-sdk-samples#25]
Hi,
i am using affective-sdk to get emotion score from video clip, referring the example video-demo .
I noticed that detector->stop at line 191(video-demo.cpp) is blocking forever or takes more than 5 minutes to stop.
This was working initially for me.
**Is this because i am using non licensed library ? or Am i missing something ?**

detector code snippet :
`std::shared_ptr<AffectivaImageListener> listenPtr(new AffectivaImageListener());//customized listener, which has csv write and  draw disabled`
` detector->setDetectAllEmotions(true);`
`detector->setDetectAllExpressions(false);`
`detector->setDetectAllEmojis(false);`
`detector->setDetectAllAppearances(false);`
`detector->setClassifierPath(AFFDEX_DATA_DIR);`
`detector->setImageListener(listenPtr.get());`
` detector->setDetectGender(false);`
`detector->setDetectAge(false);`
`detector->disableAnalytics();`
`detector->start(); `
`//GET DATA code`
`detector->stop();`

Regards,
Nikhil VS

**Comment by nikhilvs** [comment]
- Also i would like to know, what all features are missing in unlicensed version ?
- Does affdex-sdk supports hardware acceleration(on aws) ?

**Comment by umangmehta12** [comment]
* The unlicensed version gives you the option to evaluate the SDK for 60 days, after which you will need to contact us for an extended license. We are working on a series of enhancements to face detection and emotion detection that is currently available in the unlicensed version.

* Can you elaborate on what type of hardware acceleration you are looking for? It is worth mentioning that we have a REST API for video processing that we run on AWS infrastructure. Using this API you can send video data to our infrastructure for processing and retrieve the analysis in the form of a JSON or CSV. We would be happy to set you up with an account to get started.

For more information about Emotion API: https://knowledge.affectiva.com/docs/getting-started-with-the-emotion-sdk-for-the-cloud

**Comment by umangmehta12** [comment]
Re: code snippet

I am not sure what you changed from an initial code since we haven't updated the code in the repository since our last release. I think you are calling stop before checking if the detector has processed all the supplied frames. You need to implement [ProcessStatusListener](https://github.com/Affectiva/cpp-sdk-samples/blob/master/video-demo/video-demo.cpp#L151). Please refer to the documentation on how to analyze a [recorded video file](https://affectiva.readme.io/docs/analyze-a-recorded-video-file).

**Comment by nikhilvs** [comment]
@umangmehta12  

- Thanks for licensing information, more on this our marketing/management team will contact .
- When i meant h/w acceleration, ffmpeg has feature of enabling h/w acceleration by compiling it with flags  "--enable-cuda --enable-cuvid --enable-nvenc " and when run on p2,g2 or cg1 instances with corresponding driver's enabled, it will utilize GPU for processing instead of CPU.  
   **So does affective-sdk has any such configuration, as it utilizes opencv and ffmpeg ?**
   Reason for this : At the moment a file of duration 74 sec  takes around 60-67 sec on my VM, we want to improve this time.
- Regarding code snippet, i guess it was because of poor internet connection. FYI i had implemented   ProcessStatusListener as per the doc. This issue is not happening now, noticed detector->start and detector->stop was trying to contact your server's at that time.
