### ISSUE TITLE
Does not build with VS 2017

### ISSUE THREAD

**Issue by ngaloppo** [Affectiva/cpp-sdk-samples#26]
Loaded the provided solution file into VS 2017, let it convert the solution/project files. When building, I get the following error message: 

```
1>------ Build started: Project: video-demo, Configuration: Release x64 ------
1>video-demo.cpp
1>Unknown compiler version - please run the configure tests and report the results
1>video-demo.cpp(12): fatal error C1083: Cannot open include file: 'VideoDetector.h': No such file or directory
1>Done building project "video-demo.vcxproj" -- FAILED.
```

**Comment by ngaloppo** [comment]
Looks like Valloric/ycmd#656 is relevant, and indicates it would be related to the version of Boost.

**Comment by adennie** [comment]
We will be updating to a newer version of Boost in the next C++ SDK release.  In the mean time, the workaround above should work.
