### ISSUE TITLE
build fails on raspbian jessie (raspberry pi)

### ISSUE THREAD

**Issue by kaisark** [Affectiva/cpp-sdk-samples#35]
I am using OpenCV 3.1. I am running into issues building both sample apps:

opencv-webcam-demo
video-demo

cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-4.8 -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.8 -DOpenCV_DIR=/home/pi/opencv-3.1.0/build/lib -DAFFDEX_DIR=$HOME/affdex-sdk $HOME/sdk-samples
-- Setting up compiler warnings
-- Bitness detected: 32**
-- 
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   date_time
--   regex
--   thread
--   timer
--   chrono
--   serialization
--   log
--   log_setup
--   program_options
--   atomic
-- 
-- ------- SUMMARY ------- 
-- Boost version found   = 1.55.0 (105500)
--   - system         /usr/lib/arm-linux-gnueabihf/libboost_system.so
--   - filesystem     /usr/lib/arm-linux-gnueabihf/libboost_filesystem.so
--   - date_time      /usr/lib/arm-linux-gnueabihf/libboost_date_time.so
--   - regex          /usr/lib/arm-linux-gnueabihf/libboost_regex.so
--   - thread         /usr/lib/arm-linux-gnueabihf/libboost_thread.so
--   - timer          /usr/lib/arm-linux-gnueabihf/libboost_timer.so
--   - chrono         /usr/lib/arm-linux-gnueabihf/libboost_chrono.so
--   - serialization  /usr/lib/arm-linux-gnueabihf/libboost_serialization.so
--   - log            /usr/lib/arm-linux-gnueabihf/libboost_log.so
--   - log_setup      /usr/lib/arm-linux-gnueabihf/libboost_log_setup.so
--   - program_options
--                    /usr/lib/arm-linux-gnueabihf/libboost_program_options.so
-- 
-- Affdex
-- /home/pi/affdex-sdk/lib/libaffdex-native.so
-- 
-- OpenCV version found   = 3.1.0 (3.1.0)
-- OpenCV_LIB_DIR         = /home/pi/opencv-3.1.0/build/lib
--   - objdetect      opencv_xobjdetect
--   - imgproc        opencv_ximgproc
--   - objdetect      opencv_objdetect
--   - ml             opencv_ml
--   - imgproc        opencv_imgproc
--   - highgui        opencv_highgui
--   - core           opencv_core
-- 
-- Apps identified for building:
--    - opencv-webcam-demo
--    - video-demo
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/sdk-samples
..............
make video-demo
.....
[ 50%] Linking CXX executable video-demo

/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_create(unsigned int&, unsigned int)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned int) const@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::resize(unsigned int, wchar_t)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned int)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned int, unsigned int)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::logic_error::logic_error(char const*)@GLIBCXX_3.4.21'
[CMakeCache.txt](https://github.com/Affectiva/cpp-sdk-samples/files/1140343/CMakeCache.txt)
[CMakeLists.txt](https://github.com/Affectiva/cpp-sdk-samples/files/1140342/CMakeLists.txt)

**Comment by kaisark** [comment]
Environmental Variables;
[env.txt](https://github.com/Affectiva/cpp-sdk-samples/files/1140374/env.txt)

**Comment by kaisark** [comment]
pi@rpi1:~/sdk-samples $ make opencv-webcam-demo
[ 50%] Linking CXX executable opencv-webcam-demo
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_M_create(unsigned int&, unsigned int)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned int) const@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::resize(unsigned int, wchar_t)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned int)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned int, unsigned int)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'
/home/pi/affdex-sdk/lib/libaffdex-native.so: undefined reference to `std::logic_error::logic_error(char const*)@GLIBCXX_3.4.21'

**Comment by kaisark** [comment]
So, I went ahead and built gcc 6 from source alongside the existing gcc 4.8. I compiled opencv 2.4 and boost 1.55 from source. Boost and Opencv are working. I went ahead and successfully compiled the CPP SDK Samples with gcc 6. However, when I execute them the programs generate a Segmentation Fault. I ran the programs as sudo and it looks like there are some library version issues with the runtime libraries. Updating the LD_LIBRARY_PATH and PATH environmental variables did not solve the the issue.

pi@rpi2:~/sdk-samples/build/video-demo $ echo $LD_LIBRARY_PATH 
/usr/local/gcc-6.1.0/lib:/usr/lib:/home/pi/affdex-sdk/lib:/usr/lib:/home/pi/boost_1_55_0/stage/lib:/usr/local/lib:/usr/local/include:/home/pi/opencv2.4/build:/home/pi/lib/opencv2.4/release/installed/lib:/usr/local/lib

pi@rpi2:~/sdk-samples/build/video-demo $ echo $PATH
/usr/local/gcc-6.1.0/bin:/home/pi/bin:/usr/local/gcc-6.1.0/bin:/home/pi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/usr/local/lib/:/usr/local/lib/

pi@rpi2:~/sdk-samples/build/video-demo $ ./video-demo -h
Segmentation fault
pi@rpi2:~/sdk-samples/build/video-demo $ cd ../opencv-webcam-demo/
pi@rpi2:~/sdk-samples/build/opencv-webcam-demo $ ./opencv-webcam-demo 
Segmentation fault

[opencv-webcam-demo.log](https://github.com/Affectiva/cpp-sdk-samples/files/1325786/opencv-webcam-demo.log)

[video-demo.log](https://github.com/Affectiva/cpp-sdk-samples/files/1325787/video-demo.log)

**Comment by kaisark** [comment]
So, I was able to get opencv-webcam-demo and video-demo working on the Ubuntu Mate OS (ubuntu-mate.org) for RPI 3. 

pi@pi3mate:~/bin$ uname -a
Linux pi3mate 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux

gcc version = 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.5) 
Boost version =  1.58.0
OpenCV version = 2.4.8 (2.4.8)
Affdex SDK (arm) = affdex-cpp-sdk-3.1-40-linux-arm7

I did run into an issue building OpenCV 2.4.8 Video I/O (gstreamer + ffmpeg versions) and I saw that the Affdex SDK ARM build also has issues with video encoding. Anyway, I might build ffmpeg from source as a workaround. I will also try and build on Raspbian Stretch now that the OS has been released...

![affectiva1](https://user-images.githubusercontent.com/3580312/31701341-cb8d7b5a-b39d-11e7-8e74-e5dc0c51f864.png)

**Comment by jouridi2** [comment]
thank you for this tutorial 
i’m trying to analyse an image with affdex SDK (like the seconde exemple done by Abdelrahman Mahmoud )i’m using raspberry pi 3b running Raspbian stretch with gcc 6.3.0 ,but when i run the script with
./test-app image.jpg
i got this error (the same if i use .bmp image ):
segmentation fault
i tyied with an other image and i got this error :
terminate called after throwing an instance of ‘Magick::ErrorResourceLimit’
** what(): test-app: memory allocation failed `download.png’ @ error/png.c/ReadOnePNGImage/2341**
Aborted

i don’t know what to do !
have you any idea how to solve this problem ?
thank you
