### ISSUE TITLE
Cannot run video-demo and opencv-webcam-demo

### ISSUE THREAD

**Issue by Jyurei** [Affectiva/cpp-sdk-samples#43]
Hello. I have successfully built both the video-demo and opencv-webcam-demo programs, however when I attempt to run them I get nothing but this message:
Segmentation fault (core dumped)

I tried pre-loading the opencv 2.4 library, but nothing changed.
What should I do?

**Comment by umangmehta12** [comment]
@dnandha great that fixed the issue. For future reference I have created a dockerfile and attached it to the repo : https://github.com/Affectiva/cpp-sdk-samples/tree/master/docker. @Jyurei are you exporting the LD_LIBRARY_PATH=/path/to/affectiva/lib/directory

**Comment by Jyurei** [comment]
Sorry for the late reply. Yes I have tried exporting it. Here's an example of how I try to run it, maybe I'm doing something wrong:
(after running cmake)
```
/build$ make
[ 50%] Built target opencv-webcam-demo
[100%] Built target video-demo
/build$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/affdex-sdk/lib
/build$ ./video-demo/video-demo -i '/home/yolo/Documents/EP02_04f.avi' 
Segmentation fault (core dumped)

```
Maybe I'm not passing the arguments right? Thank you.

**Comment by Jyurei** [comment]
I tried running it like this and got a different error message:
```
~/build$ ./video-demo/video-demo -d '/home/yolo/affdex-sdk/data' -i '/home/yolo/Documents/EP03_02f.avi' 
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::logic_error> >'
  what():  character conversion failed
Aborted (core dumped)

```

**Comment by umangmehta12** [comment]
I am going to close this due to lack of activity, feel free to open this in case if you run into issues.
