### ISSUE TITLE
Encountered an AffdexException：Unable to initialize affdex

### ISSUE THREAD

**Issue by hetingjane** [Affectiva/cpp-sdk-samples#51]
I'm running the affdex-win-samples.sln provided by the sample file through VS2017 on a 64-bit Windows system, I've already set the include directory and library directory, etc. I'm using opencv 3.4 and boost 1.59 (because it can't find libboost_filesystem-vc120-mt-1_59.lib when I use the latest version boost)

My arguments are set to: -d D:\code\cpp-sdk-samples-emotion-sdk\data\joy.mp4 -r 640 480
where the path is where I put my test video 

The opencv-webcam-demo and video-demo both give me this on the terminal:
Initializing Affdex FrameDetector
Setting the webcam frame rate to: 30
Max num of faces set to: 1
Face detector mode set to: LARGE_FACES
Encountered an AffdexException Failed to initialize: Unable to initialize affdex

how to fix the last line problem? Thanks for your help!

**Comment by umangmehta12** [comment]
I would suggest looking at the README for instructions on how to run the sample apps.
OpenCV webcam demo: https://github.com/Affectiva/cpp-sdk-samples#opencv-webcam-demo-c
Video demo: https://github.com/Affectiva/cpp-sdk-samples#video-demo-c

The video-demo utility expects an input file (-i) and the path to the directory consisting of the Affectiva SDK models (-d).

Please go over the dependencies for the sample apps as well (https://github.com/Affectiva/cpp-sdk-samples#additional-dependencies)

`opencv-webcam-demo.exe -d C:\Path\To\AffdexSDK\data` and
`video-demo.exe -d C:\Path\To\AffdexSDK\data -i C:\Path\To\Input\video.mp4`

By default the screen resolution is 640x480.

**Comment by adennie** [comment]
Hi, would you mind sharing the video that resulted in that error?  We'll investigate.

**Comment by hetingjane** [comment]
I'm sorry that's my fault! The problem goes from the empty frame in my previous video, I recorded a new video which my head stay relatively clear and stable in the center and the problem was fixed. Thank you so much!

**Comment by adennie** [comment]
Well, it shouldn't produce an error like that anyway, but thanks for the tip, we'll try to reproduce with an empty frame.

**Comment by adennie** [comment]
Rats, I can't seem to reproduce it; I'm moving my head all over the place and in/out of the frame :-).  Do you still have the first video that causes the probem?

**Comment by hetingjane** [comment]
[test.zip](https://github.com/Affectiva/cpp-sdk-samples/files/2113699/test.zip)
I think it's the problem of the video

**Comment by adennie** [comment]
Hi thanks for the test video.  I still haven't been able to reproduce the problem, unfortunately.  When I look at the frame in that video with timestamp 1.7s, it doesn't look like an empty frame.  I just want to confirm that this is the video that gave you that error.

**Comment by hetingjane** [comment]
Hi, that's weird because every time I test using that video I receive the error, but the program works fine when I use other videos.

**Comment by hetingjane** [comment]
Sorry I encountered a problem again :) the video-demo works but the webcam-demo (in the same solution as video-demo) doesn't work
I followed all the instructions you suggested above and compiled the opencv-webcam-demo in VS2017, and I got 
![error1](https://user-images.githubusercontent.com/37964198/42246726-e8bf0140-7eda-11e8-820c-50c25e94b123.jpg)
when I run the exe file, nothing shown in the window
![error2](https://user-images.githubusercontent.com/37964198/42246859-7c3d377a-7edb-11e8-8612-38ccb2f0f9a5.png)
any help will be greatly appreciated!

**Comment by adennie** [comment]
Hi, usually that error indicates that the data directory path you specified on the command line is not pointing to a valid data directory.
