### ISSUE TITLE
Capture results on 1 machine and show them on other machine????

### ISSUE THREAD

**Issue by manojcute009** [Affectiva/cpp-sdk-samples#58]
Dear All,

Need your help regarding mentioned issue. I have captured webcam data on client machine. Now I want to show emotions and picture of client on Agents machine. So what are the process for this using javascript and java.

Any help is really appreciated.

Thanks

**Comment by umangmehta12** [comment]
Sorry for the delayed response. Closing this now since we do not have a way to do that. Feel free to open a enhancement request.
