### ISSUE TITLE
Runtime HighGui Error - HIGHGUI ERROR: V4L/V4L2: VIDIOC_S_CROP

### ISSUE THREAD

**Issue by kawa-marcin** [Affectiva/cpp-sdk-samples#8]
My operating system is a server version of Ubuntu 14.04. A simple example compile without issues but when I'm trying to run the executable I'm getting this error:

```
$ LD_LIBRARY_PATH=$HOME/affdex-sdk/lib ./main
HIGHGUI ERROR: V4L/V4L2: VIDIOC_S_CROP
terminate called without an active exception
Aborted (core dumped)
```

Any help would be appreciated.

**Comment by umangmehta12** [comment]
Is this resolved now? The issue is it is not able to find the HIGHGUI library used by OpenCV. Can you highlight the version of OpenCV that you are using?

**Comment by kawa-marcin** [comment]
Hi, thanks for the reply. I'm not working on this project any more so the issue can be closed.
Though if I remember correctly the issue was related to `libv4l-dev` missing or wrong version. After updating and compilation of OpenCV problem went away.

**Comment by aniketmore234** [comment]
I too got the same issue 
<code>
aniket@aniket-HP-Pavilion-Notebook:~/affdex-sdk/build/opencv-webcam-demo$ ./opencv-webcam-demo -d ~/affdex-sdk/data
Hit ESCAPE key to exit app..
Initializing Affdex FrameDetector
HIGHGUI WARNING: V4L/V4L2: VIDIOC_S_CROP
HIGHGUI WARNING: V4L: setting property #5 is not supported
HIGHGUI WARNING: V4L/V4L2: VIDIOC_S_CROP
Setting the webcam frame rate to: 30
Max num of faces set to: 1
Face detector mode set to: LARGE_FACES
Segmentation fault (core dumped)
</code>
I am using opencv 3.0.0 How to fix this?

**Comment by umangmehta12** [comment]
@aniketmore234 the app uses OpenCV 2.4, you will have to downgrade.
